#A pipeline is made up of one or more stages
#A stage is a way of organizing jobs in a pipeline and each stage can have one or more jobs
#trigger: none: This specifies that the pipeline does not have an automatic trigger associated with it.
#pool: Defines the agent pool and operating system image for the pipeline jobs.
#steps: Defines the sequence of tasks or commands to be executed in the pipeline.

# stages: defines the different stages of the pipeline. 
# Stages allow you to break down your pipeline into logical sections, 
# typically representing different phases or environments of your deployment process.


trigger: none

pool:
  vmimage: 'ubuntu-18.04'

steps:
- script: echo 'Hello world'


