# Dependencies Example
# 'dependsOn: []' removes the implicit dependency on previous stages, making this stage run in parallel.


# For more details about 'trigger', refer to the file: 001-trigger-pr-pool.yaml
trigger: none


# For more details about 'pool', refer to the file: 001-trigger-pr-pool.yaml
pool:
  vmimage: 'ubuntu-18.04'

stages:  #For more details about 'stage', refer to the file: 003-different-stages-jobs.yaml
- stage: car
  jobs:
  - job: car-latest
    steps:
    - script: echo 'car-latest'

  - job: car-old
    steps:
    - script: echo 'car-old'

- stage: byke
  dependsOn: []  # This removes the implicit dependency on the previous stages
  jobs:
  - job: byke-latest
    steps:
    - script: echo 'byke-latest'
  
  - job: byke-old
    steps: 
    - script: echo 'byke-old'
