trigger: none

pool:
  vmimage: 'ubuntu-18.04'

stages:
- stage: iOS
  jobs:
  - job: iOS-18
    steps:
    - script: echo 'iOS-18'

  - job: iOS-17
    steps:
    - script : echo 'iOS-17'

- stage: Windows
  dependsOn: iOS # stage 'Windows' Dependencies on Stage 'iOS'
  jobs:
  - job: Windows-11
    steps:
    - script : echo 'Windows-11'
  
  - job: Windows-10
    steps: 
    - script: echo 'Windows-10'

- stage: macOS
  dependsOn: iOS #stage 'macOS' Dependencies on Stage 'iOS'
  jobs:
  - job: macOS-11
    steps:
    - script : echo 'macOS-11'
  
  - job: macOS-12
    steps: 
    - script: echo 'macOS-12'

- stage: Ubuntu
  dependsOn:
  - Windows
  - macOS  ##stage 'Ubuntu' Dependencies on Stage 'Windows' and 'macOS'
  jobs:
  - job: Ubuntu-24
    steps:
    - script : echo 'Ubuntu-24'
  
  - job: Ubuntu-23
    steps: 
    - script: echo 'Ubuntu-23'