# Each job has its own pool definition specifying a different VM image

trigger: none

pool:
  vmimage: 'ubuntu-18.04'

stages:
- stage: iOS

  jobs:
  - job: Windows
    pool:
      vmimage: 'windows 11'
    steps:
    - script: echo 'iOS'

  - job: macOS
    pool:
      vmimage: 'ubuntu-18.04'
    steps:
    - script : echo 'macOS'

  - job: linux
    pool:
      vmimage: 'linux-18.04'
    steps:
    - script : echo 'linux'