trigger: none

pool:
  vmimage: 'ubuntu-18.04'

stages:
- stage: iOS
  jobs:
  - job: myjob
    timeoutInMinutes: 1
    steps:
    - task: InlinePowerShell@1
      inputs:
        script: |
          Write-Output 'Going to sleep'
          Start-Sleep -s 180
          write-Output 'Waking Up'

timeoutInMinutes: 1 sets a timeout of 1 minute for the job myjob. If the job execution exceeds this limit, 
                  it will be automatically terminated.

# The timeout of 1 minute specified for myjob suggests that even though the sleep duration is 180 seconds, 
# the job itself is expected to complete within 1 minute. If the sleep duration exceeds 1 minute, 
# the job will be forcibly terminated due to the timeout setting.